sudo: required
dist: trusty
# Force travis to use its minimal image with default Python settings
language: generic
compiler:
  - gcc
env:
  global:
    - CATKIN_WS=~/catkin_ws
    - CATKIN_WS_SRC=${CATKIN_WS}/src
    - CI_ROS_DISTRO="indigo"

branches:
  only:
    - indigo_dev
notifications:
  email: false
install:
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu trusty main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-rosdep python-catkin-tools
  - sudo rosdep init
  - rosdep update
  
  - mkdir -p $CATKIN_WS_SRC
  - ln -s $TRAVIS_BUILD_DIR $CATKIN_WS_SRC

  - cd $CATKIN_WS_SRC
  - git clone https://github.com/koellsch/obstacle_distance.git

  # Use rosdep to install all dependencies (including ROS itself)
  - rosdep install --from-paths ./ -i -y --rosdistro $CI_ROS_DISTRO
  - source /opt/ros/$CI_ROS_DISTRO/setup.bash

  - cd $CATKIN_WS_SRC
  - catkin_init_workspace
  - cd $CATKIN_WS
  - catkin_make
  - source devel/setup.bash
script:
